In [1]:
pwd

'/Users/Vaishnavi_Home/Desktop/cms-workshop'

In [2]:
ls

Etot.txt
Untitled1.ipynb
Untitled2.ipynb
data/
energies.txt
file_name.txt
processing multiple files and writing files.ipynb
working with tabular data.ipynb


In [3]:
cd data

/Users/Vaishnavi_Home/Desktop/cms-workshop/data


In [4]:
ls

03_Prod.mdout              buckminsterfullerene.xyz
Untitled.ipynb             distance_data_headers.csv
Untitled1.ipynb            outfiles/
Untitled2.ipynb            sapt.out
benzene.xyz                water.xyz


In [5]:
import os
file = os.path.join('distance_data_headers.csv')
lines = open(file, 'r')
data = lines.readlines()
lines.close()
print(data)

['Frame,THR4_ATP,THR4_ASP,TYR6_ATP,TYR6_ASP\n', '1,8.9542,5.8024,11.5478,9.9557\n', '2,8.6181,6.0942,13.9594,11.6945\n', '3,9.0066,6.0637,13.0924,11.3043\n', '4,9.2002,6.0227,14.5282,10.1763\n', '5,9.1294,5.9365,13.5321,10.6279\n', '6,9.0462,6.2553,13.906,10.4292\n', '7,8.8657,5.9186,12.9312,10.2176\n', '8,9.3256,6.2351,13.0721,10.474\n', '9,9.4184,6.1993,13.2614,10.366\n', '10,9.06,6.0478,13.4953,11.0118\n', '11,8.1294,6.1297,12.8852,10.8787\n', '12,8.4913,5.9893,12.1967,10.453\n', '13,8.531,5.5447,12.923,10.1537\n', '14,8.1888,6.051,12.8918,10.8688\n', '15,8.4061,5.897,13.3561,10.7441\n', '16,7.6663,5.8643,12.2005,11.2915\n', '17,8.3618,5.7622,12.6091,10.7489\n', '18,7.7215,5.6508,12.5267,10.6546\n', '19,8.2899,6.0158,12.4332,11.0468\n', '20,7.5783,5.8658,11.6183,11.1414\n', '21,8.11,5.9668,11.2731,10.4215\n', '22,7.6321,5.9912,11.7955,11.5002\n', '23,7.9411,5.9731,11.879,10.469\n', '24,8.1973,6.0981,12.1157,10.8132\n', '25,8.2322,5.7608,12.1537,10.3618\n', '26,8.269,5.8867,12.6649,1

In [7]:
import numpy
help(numpy.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [10]:
import os 

distance_file = os.path.join('distance_data_headers.csv')

distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype='unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [11]:
headers = distances[0]
print(headers)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


In [13]:
slice_data = distances[1:]
print(slice_data)

[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [14]:
data = slice_data.astype(numpy.float)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [15]:
small_data = data[0:10, 0:3]
# row and then column
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [17]:
thr4_atp = data[:,1] # every row, just THR4_ATP column
avg_thr4_atp = numpy.mean(thr4_atp)
print(avg_thr4_atp)

10.876950930000001


In [19]:
num_columns = len(data[0,:]) # number of columns
print(num_columns)

5


In [20]:
for i in range(1, num_columns):
    column = data[:,i]
    avg_col=numpy.mean(column)
    print(F'{headers[i]} : {avg_col}')

THR4_ATP : 10.876950930000001
THR4_ASP : 7.342344959999999
TYR6_ATP : 11.209791329999998
TYR6_ASP : 10.9934435


In [21]:
ls

03_Prod.mdout              buckminsterfullerene.xyz
Untitled.ipynb             distance_data_headers.csv
Untitled1.ipynb            outfiles/
Untitled2.ipynb            sapt.out
benzene.xyz                water.xyz


In [24]:
file = os.path.join('water.xyz')
lines = open(file, 'r')
data = lines.readlines()
lines.close()
print(data)

['3\n', 'Water xyz file\n', 'O        0.000000     -0.007156      0.965491\n', 'H1      -0.000000      0.001486     -0.003471\n', 'H2       0.000000      0.931026      1.207929\n']


In [25]:
import numpy
import os

In [26]:
xyz_file = numpy.genfromtxt(fname=file, skip_header=2, dtype='unicode')

In [27]:
symbols = xyz_file[:,0]

In [28]:
print(symbols)

['O' 'H1' 'H2']


In [29]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [30]:
coordinates=(xyz_file[:,1:])

In [31]:
print(coordinates)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [32]:
coordinates=coordinates.astype(numpy.float)

In [33]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [39]:
num_atoms=len(symbols)
print(num_atoms)

3


In [57]:
BLfile = open('bond_lengths.txt', 'w+')
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2: 
            x_distance = coordinates[num1,0]-coordinates[num2,0]
            y_distance=coordinates[num1,1]-coordinates[num2,1]
            z_distance=coordinates[num1,2]-coordinates[num2,2]
            bond_length=numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)

            if bond_length>0 and bond_length <= 1.5:
                BLfile.write(F'{symbols[num1]} to {symbols[num2]} : {bond_length:.2f}')
BLfile.close()